services:
  api_task_assignment:
    build:
      context: .
      target: development
    command: npm run dev
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT:-3000}
      DB_HOST: ${DB_HOST:-api_task_assignment_db}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-task_assignment}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      # Used for Prisma
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@api_task_assignment_db:5432/task_assignment}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - api_task_assignment_db

  api_task_assignment_db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-task_assignment}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
