// Sample endpoints, can use REST Client extension on VS Code to run this, or run via curl / postman / etc.

@baseUrl = http://localhost:3000
@taskId = 7a5e9113-bbe9-42cc-9ce5-f6035f77461e

// Get skills
GET {{baseUrl}}/skills

###
// Get developers
// Optional query parma: skill, eg. ?skill=1 or ?skill=1,2
GET {{baseUrl}}/developers

###
// Get all statuses
GET {{baseUrl}}/statuses

###
// Get tasks
GET {{baseUrl}}/tasks

###
// Get task by task id
GET {{baseUrl}}/tasks/60a7aa66-8eed-499b-be7f-78ac158d8094

###
// Create task. Will assign default statusId 1 (Backlog) for simplicity, since requirement did not state need to assign status during task creation.
// There are complexities when user first create parent task with status Done, then create a subtask without being status Done.
// May be a bad user experience because user intended for parent task to be status Done.
// Will also remove "assignee" field (developer). If the skills is empty, we may be assigning a task to a developer who does not have a skill.
// Will just rely on update developer endpoint to update asignee.
POST {{baseUrl}}/tasks
{
    "title": "Mock title", // Required
    "skills": [1], // Field optional. If none, use LLM. Means under thsi tasks endpoint, should also call LLM?
    "parentTaskId": "xxx-xxx", // Optional. If creating a child subtask standalone (we may not need it though?)
    // subtasks is optional, only when we want to create child task in one shot
    "subtasks": [
        {
            "title": "Mock title", // Required
            "skills": [1], // Field optional. If none, use LLM. Means under thsi tasks endpoint, should also call LLM?
        }
    ]
}

###
POST {{baseUrl}}/tasks
content-type: application/json

{
    "title": "As a user, I want to use this website on my mobile and tablet",
    "skills": [1],
    "subtasks": [
        {
            "title": "As an analyst, I want to analyse user behaviour",
            "skills": [1,2],
            "subtasks": [
                {
                    "title": "As a user, I want to customise profile"
                }
            ]
        },
        {
            "title": "As an analyst, I want to see clickstream data."
        }
    ]
}


###
// Update task's status
// Have some constraints: If there is subtask, all the subtask (and nested subtasks) must be "Done" before this task can be Done.
PATCH {{baseUrl}}/tasks/60a7aa66-8eed-499b-be7f-78ac158d8094/status
content-type: application/json

{
    "statusId": 3
}

###
// Update task's assignee (developer)
// Have some constraints: Task can only be assigned to assignee with skills(s) required by task.
// Means, the task should have at least 1 skill assigned to it... Else throw error?
PATCH {{baseUrl}}/tasks/35592a96-1b81-4982-b730-5c4f07306e79/developer
content-type: application/json

{
    "developerId": "aa9beae9-336d-46ce-aafb-74c88992a568"
}

###
// Unassign task's assignee (developer)
DELETE {{baseUrl}}/tasks/7a5e9113-bbe9-42cc-9ce5-f6035f77461e/developer

###
// Gemini
GET {{baseUrl}}/gemini
